<?php

namespace Tests\Feature;

use App\Repositories\UserRepositoryInterface;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;

class AccessTest extends TestCase
{
    use DatabaseMigrations;

    protected static bool $setUpHasRunOnce = false;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Migrate DB only once - prevent doing this before each test
        if (!static::$setUpHasRunOnce) {
            $this->runDatabaseMigrations();
            static::$setUpHasRunOnce = true;
        }
    }

    /**
     * Unauthenticated user cannot reach following pages
     * @return void
     */
    public function test_cannot_reach_protected_pages(): void
    {
        // Listed some pages with restricted access, expected redirect (status 302)
        $this->get(route('home'))->assertStatus(302);
        $this->get(route('clients'))->assertStatus(302);
        $this->get(route('projects'))->assertStatus(302);
        $this->get(route('timesheet'))->assertStatus(302);
        $this->get(route('userActivities'))->assertStatus(302);
    }

    public function test_can_reach_protected_pages(): void
    {
        // Get user repository
        $userRepository = $this->app->make(UserRepositoryInterface::class);

        // Create first account
        $user = $userRepository->addGoogleUser('test', str::random(5) . '@gmail.com', Hash::make('password'));
        $this->be($user);

        // User can log into his account
        $this->assertTrue(Auth::check());

        // Listed some pages with restricted access, that can be seen (status 200)
        $this->get(route('home'))->assertStatus(200);
        $this->get(route('clients'))->assertStatus(200);
        $this->get(route('projects'))->assertStatus(200);
        $this->get(route('timesheet'))->assertStatus(200);
        $this->get(route('userActivities'))->assertStatus(200);
    }
}
