<?php

namespace Tests\Feature;

use App\Repositories\UserActivityRepositoryInterface;
use App\Repositories\UserRepositoryInterface;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Tests\TestCase;

class UserActivityTest extends TestCase
{
    use DatabaseMigrations;

    protected static $setUpHasRunOnce = false;

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        // Migrate DB only once - prevent doing this before each test
        if (!static::$setUpHasRunOnce) {
            $this->runDatabaseMigrations();
            static::$setUpHasRunOnce = true;
        }
    }

    /**
     * The application does not log seen pages by unauthenticated user
     * @return void
     */
    public function test_unknown_user_cannot_log_seen_page(): void
    {
        // Get user repository
        $userActivityRepository = $this->app->make(UserActivityRepositoryInterface::class);

        // Trigger page open
        $this->get(route('home'))->assertStatus(302);
        $lastActivity = $userActivityRepository->getLast();

        $this->assertNull($lastActivity);
    }

    /**
     * The application does log seen pages by authenticated user
     * @return void
     */
    public function test_authenticated_user_can_log_seen_page(): void
    {
        // Get UserActivityRepositoryInterface
        $userActivityRepository = $this->app->make(UserActivityRepositoryInterface::class);

        // Get UserRepositoryInterface
        $userRepository = $this->app->make(UserRepositoryInterface::class);

        // Create first account
        $user = $userRepository->addGoogleUser('test', str::random(5) . '@gmail.com', Hash::make('password'));
        $this->be($user);

        // Trigger page open
        $this->get(route('home'));
        $lastActivity = $userActivityRepository->getLast();

        // Is returned object
        $this->assertIsObject($lastActivity);

        // Is '/' latest seen page (dashboard path)
        $this->assertEquals('/', $lastActivity->page);

        // Is 'seen' type
        $this->assertEquals('Seen', $lastActivity->type);
    }
}
